# Generated by Django 3.1.5 on 2021-08-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=10000)),
                ('sell_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('buy_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('num_of_items', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
