# Generated by Django 3.1.5 on 2021-08-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_factory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
