# Generated by Django 3.2.6 on 2021-08-12 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210812_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='sold_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateField()),
                ('discounts', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
