# Generated by Django 3.1.5 on 2021-08-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sold_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_products',
            name='sold_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
