# Generated by Django 3.2.6 on 2021-08-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210812_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(default='', max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
