# Generated by Django 3.1.5 on 2021-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210812_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
