# Generated by Django 3.1.5 on 2021-08-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210812_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='num_of_items',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='sold_products',
            name='discounts',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='sold_products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
    ]
