# Generated by Django 3.1.5 on 2021-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210812_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_products',
            name='sold_date',
            field=models.DateTimeField(),
        ),
    ]
