# Generated by Django 3.2.6 on 2021-08-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210812_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
                ('Date', models.DateTimeField(default='')),
            ],
        ),
    ]
