# Generated by Django 3.2.6 on 2021-08-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='Date',
            field=models.DateField(default=''),
        ),
    ]
