# Generated by Django 3.2.6 on 2021-08-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_profit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='Date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
