# Generated by Django 3.2.6 on 2021-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold_products',
            name='product_info',
        ),
        migrations.AddField(
            model_name='sold_products',
            name='name',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='sold_products',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='sold_products',
            name='sold_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
