# Generated by Django 3.2.6 on 2021-08-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_sold_products_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_products',
            name='product_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
