# Generated by Django 3.2.6 on 2021-08-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_sold_products_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_products',
            name='sold_date',
            field=models.DateTimeField(),
        ),
    ]
