# Generated by Django 3.2.6 on 2021-08-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_sold_products_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_products',
            name='sold_date',
            field=models.DateField(default='17.08.2021 11:55:22'),
        ),
    ]
