# Generated by Django 3.2.6 on 2021-08-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_sold_products_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_products',
            name='sold_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
