# Generated by Django 3.2.6 on 2021-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_sold_products_sold_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_products',
            name='year_month_day_solds',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
