# Generated by Django 3.2.6 on 2021-08-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_returns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='returns',
            new_name='Returns_products',
        ),
    ]
