# Generated by Django 3.2.6 on 2021-08-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_rename_returns_returns_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
            ],
        ),
    ]
