# Generated by Django 3.2.6 on 2021-08-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
