# Generated by Django 3.2.6 on 2021-08-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210819_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='products_inTheInVentory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=19, null=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=19, null=True)),
                ('num_of_items', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
                ('factory_name', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
    ]
