# Generated by Django 3.2.6 on 2021-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_products_intheinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='Customer_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='Date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='product_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='product_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
