# Generated by Django 3.2.6 on 2021-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20210821_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=200)),
                ('product_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Date', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
