# Generated by Django 3.2.6 on 2021-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210821_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='num_of_items',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='products_intheinventory',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='products_intheinventory',
            name='num_of_items',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='products_intheinventory',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sold_products',
            name='discounts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='sold_products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='sold_products',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
