# Generated by Django 3.2.6 on 2021-08-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_users_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
