# Generated by Django 3.2.6 on 2021-08-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='expenses',
        ),
    ]
