# Generated by Django 3.2.6 on 2021-08-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_expenses_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses_details',
            name='Date',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
