# Generated by Django 3.2.6 on 2021-08-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_expenses_details_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
    ]
