# Generated by Django 3.2.6 on 2021-08-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_profit_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit',
            name='expenses',
        ),
    ]
