# Generated by Django 3.2.6 on 2021-08-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_alter_bills_numofitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold_products',
            name='discounts',
        ),
        migrations.AddField(
            model_name='sold_products',
            name='num_of_items',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True),
        ),
    ]
