# Generated by Django 3.2.6 on 2021-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20210825_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='dialyProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
        ),
    ]
